services:
  me:
    image: me:latest
    init: true
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=5000
      - INDEXER_PORT=3000
      - MATCHING_ENGINE_PATH=matching_engine
      - SUPERVISORD_PATH=/app/supervisord
      - SKIP_VERIFICATION=true
    volumes:
      - /app/ecdsa.sec:/app/ecdsa.sec
